name: Your New Jekyll Site
markdown: redcarpet
pygments: true
port: 5000
permalink: /blog/:year/:month/:day/:title/

# For Github Pages
base_folder: /create_a_blog_in_30_minutes_using_jekyll
base_url: http://localhost:5000